[tool.poetry]
name = "crypto-trade-bot"
version = "0.1.0"
description = "Bot de Trading de Criptomoedas Avançado"
authors = ["Seu Nome <seu.email@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.0"
uvicorn = "^0.28.0"
pydantic = "^2.6.1"
pydantic-settings = "^2.1.0"
sqlalchemy = "^2.0.27"
asyncpg = "^0.29.0"
ccxt = "^4.1.81"
redis = "^5.0.1"
pandas = "^2.2.0"
numpy = "^1.26.3"
polars = "^0.20.6"
ta-lib = "^0.4.28"
scikit-learn = "^1.4.0"
pytorch = "^2.2.0"
httpx = "^0.27.0"
websockets = "^12.0"
pytest = "^8.0.0"
pytest-asyncio = "^0.23.4"
python-dotenv = "^1.0.0"
loguru = "^0.7.2"
prometheus-client = "^0.19.0"
aiokafka = "^0.10.0"
opentelemetry-api = "^1.22.0"
opentelemetry-sdk = "^1.22.0"

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
isort = "^5.13.2"
mypy = "^1.8.0"
flake8 = "^7.0.0"
pytest-cov = "^4.1.0"
pre-commit = "^3.6.0"
bandit = "^1.7.6"
sphinx = "^7.2.6"
mkdocs = "^1.5.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true